import type { Guia } from '../guia';

export const GUIA_FACTURACION: Guia = {
  id: 'facturacion',
  titulo: 'Facturación',
  modulo: 'Facturación',
  ruta: '/facturacion',
  resumen: 'La suma de la gestoría de los casos abiertos, la emisión de facturas y el cierre controlado de cada caso.',
  paraQue:
    'Facturar lo trabajado, llevar el control de qué está cobrado, y cerrar cada caso solo cuando sus cuentas cuadran.',
  aSaber: [
    'Las facturas de un caso salen de los movimientos registrados en su pestaña "Gestoría".',
    'Con Verifactu activado, el NIF del cliente es obligatorio y la factura enviada a la AEAT ya no se puede editar.',
    'El "Modo sandbox" envía a las pruebas de la AEAT, no al entorno real.',
    'Cerrar un caso lo pasa a "Archivo"; desde ahí "Reabrir" lo devuelve a los casos abiertos.',
  ],
  claves: ['facturas', 'cobros', 'honorarios', 'verifactu', 'aeat', 'iva', 'cierre de caso'],
  tareas: [
    {
      id: 'facturar-caso',
      titulo: 'Generar la factura de un caso',
      claves: ['emitir factura', 'crear factura', 'facturar', 'cobrar', 'líneas', 'cliente', 'nif', 'razón social'],
      requiere: { modulo: 'Facturación', capacidad: 'crear' },
      pasos: [
        'En Facturación, ve a la pestaña "Casos abiertos".',
        'En la fila del caso, pulsa "Generar factura". Si el caso ya tiene alguna, el botón dice "Nueva factura".',
        'En la sección "Cliente", revisa los datos que Vertey precarga del contacto del caso: "Nombre o razón social", "Tipo de documento", "Número de documento" (el NIF) y "Dirección". Puedes corregirlos aquí; son los que se imprimen en la factura.',
        'Si corriges el NIF y quieres conservarlo en la ficha del contacto, deja marcado "Guardar también en el contacto". Solo se actualiza el documento, no el resto de sus datos.',
        'Indica la "Fecha emisión", la "Fecha vencimiento" y la "Tasa de IVA (%)".',
        'En "Líneas", pulsa "Agregar línea" y escribe el concepto, la "Cantidad" y el "Precio Ud.".',
        'Revisa la "Base imponible", el IVA y el "Total".',
        'Pulsa "Generar factura".',
      ],
      nota: 'Si el despacho tiene Verifactu activado, el NIF del cliente es obligatorio y la factura se registra automáticamente en la AEAT; después ya no puede editarse. Si el NIF no es válido (números o letra de control), Vertey no deja generar la factura hasta que lo corrijas. Verifactu aún no admite documentos extranjeros (pasaporte, VAT u otro): con "Documento extranjero" la factura se guarda, pero no se envía a la AEAT.',
    },
    {
      id: 'factura-libre',
      titulo: 'Crear una factura que no pertenece a ningún caso',
      claves: ['factura libre', 'factura suelta', 'sin caso', 'standalone', 'cliente puntual', 'buscar contacto', 'nif'],
      requiere: { modulo: 'Facturación', capacidad: 'crear' },
      pasos: [
        'En la cabecera de Facturación, pulsa "Nueva factura".',
        'En la sección "Cliente", escribe en "Buscar contacto" el nombre, el NIF, el email o el teléfono de un contacto y elígelo de la lista (con las flechas y Enter, o con el ratón): sus datos se precargan.',
        'Si no es un contacto de tu cartera, déjalo en blanco y escribe a mano el "Nombre o razón social", el "Número de documento" y la "Dirección": es un cliente puntual y no se crea ningún contacto. Con "Quitar contacto" vuelves a este modo.',
        'Si elegiste un contacto y quieres guardarle el documento que acabas de indicar, deja marcado "Guardar también en el contacto".',
        'Rellena las fechas, la tasa de IVA y las líneas igual que en una factura de caso.',
        'Pulsa "Generar factura".',
      ],
      nota: 'Con Verifactu activado el NIF del cliente es obligatorio y debe ser un NIF español válido. Verifactu aún no admite documentos extranjeros: con "Documento extranjero" la factura se guarda, pero no se envía a la AEAT.',
    },
    {
      id: 'gestionar-facturas',
      titulo: 'Buscar, descargar y cobrar facturas',
      claves: ['pdf', 'descargar', 'pagada', 'cobrada', 'borrador', 'rectificativa', 'anular', 'listado'],
      pasos: [
        'Ve a la pestaña "Facturas".',
        'Filtra con "Buscar" (número, cliente o caso), "Estado", "Desde" y "Hasta".',
        'En cada factura tienes "Descargar PDF" y "Copiar enlace PDF".',
        'Según su estado, también "Editar factura", "Finalizar borrador", "Marcar como pagada", "Crear rectificativa" y "Anular factura".',
        'Al editar un borrador puedes corregir los datos de la sección "Cliente". La rectificativa mantiene el mismo cliente que la factura original y no se puede cambiar.',
      ],
      nota: 'Las acciones que cambian una factura requieren permiso de edición en Facturación.',
    },
    {
      id: 'cerrar-caso-facturacion',
      titulo: 'Cerrar un caso y pasarlo al archivo',
      claves: ['cierre', 'archivar', 'finalizar caso', 'reabrir'],
      requiere: { modulo: 'Facturación', capacidad: 'editar' },
      pasos: [
        'En la pestaña "Casos abiertos", pulsa "Cerrar caso" en la fila del caso.',
        'Marca las dos confirmaciones: que los movimientos financieros están contemplados y que el saldo está corroborado en bancos.',
        'Confirma el cierre. El caso pasa a la pestaña "Archivo".',
      ],
      nota: 'Puedes cerrar un caso sin factura, aunque se recomienda facturar antes. Desde "Archivo", "Reabrir" lo devuelve a los casos abiertos.',
    },
    {
      id: 'registro-horas',
      titulo: 'Consultar las horas declaradas y lo pendiente de facturar',
      claves: ['horas', 'tiempo', 'sin facturar', 'valor pendiente', 'timesheet'],
      pasos: [
        'Ve a la pestaña "Registro de Horas".',
        'Arriba ves las "Horas totales", las que están "Sin facturar" y el "Valor pendiente".',
        'La tabla detalla cada registro por fecha, caso e hito, miembro, horas e importe.',
      ],
      nota: 'Las horas se registran desde el Calendario, en cada hito.',
    },
    {
      id: 'configurar-facturacion',
      titulo: 'Configurar los datos de facturación y Verifactu',
      claves: ['datos fiscales', 'razón social', 'verifactu', 'aeat', 'certificado digital', 'sandbox', 'emisor'],
      requiere: { modulo: 'Facturación', capacidad: 'editar' },
      pasos: [
        'En Facturación, pulsa "Configuración".',
        'En "Datos de facturación", elige el "Tipo de persona" y escribe el "Nombre / Razón social".',
        'En "Verifactu (AEAT)", marca "Activar envío automático a AEAT" si quieres registrar las facturas en Hacienda.',
        'Sube el "Certificado digital AEAT" y guarda los cambios.',
      ],
      nota: 'El "Modo sandbox" envía las facturas al entorno de pruebas de la AEAT, no al real. Úsalo solo para probar.',
    },
  ],
};
